### ISSUE TITLE
Please use `Visitor.getInstance` to instantiate Visitor

### ISSUE THREAD

**Issue by DanTylkowski** [brightcove/videojs-omniture#2]
Hello,

I am trying to use this plugin and got the following error:
`Please use `Visitor.getInstance` to instantiate Visitor`

Digging around on google a bit, I found this documentation:
https://marketing.adobe.com/resources/help/en_US/mcvid/mcvid_getinstance.html

It looks like it's trying to use an outdated way of instantiating the connection to Omniture. 

Is there anybody who can help me with this?

I'm pasting the documented URLs into the player plugins section of the CMS and the rest of my code matches how the documentation says to use this plugin.

Thanks.

**Comment by misteroneill** [comment]
Sorry, but we are not actively maintaining this repository. It should have been archived years ago, but it wasn't!
